### ISSUE TITLE
CI deployment not working in all PRs

### ISSUE THREAD

**Issue by lilyminium** [lilyminium/mdanalysis-sphinx-theme#23] opened 2023-08-21 06:38 UTC
It may depend on who opens the PR?
Example: https://github.com/MDAnalysis/mdanalysis-sphinx-theme/pull/22

**Comment by IAlibay** [comment] 2023-08-28 10:29
I think this is expected behaviour? At least from the context provided here it looks like github protecting you from outside authors trying to push to the website by just opening a PR.

Do you really want to be pushing to the website during a PR instead of just doing it on merge?

**Comment by lilyminium** [comment] 2023-08-28 11:38
Yeah, the correct answer here may be to just not fail CI if the author isn't allowed. I kept the push because some things do render differently on RTD and not sure how best to preview otherwise. We could keep it as an artifact, maybe.

**Comment by IAlibay** [comment] 2023-09-04 00:22
Fixed by #38

**Closed as completed by IAlibay** 2023-09-04 00:22 UTC
